openapi: 3.0.0
info:
  title: Nalobin Igor
  version: 1.0.0
  description: |
    ## API CV

servers:
  - url: https://igor-nalobin.github.io/igor-nalobin

paths:
  /about:
    get:
      summary: Common
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: 
                $ref: "https://raw.githubusercontent.com/igor-nalobin/igor-nalobin/main/data/about.json"

  /skills:
    get:
      summary: Skills
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: 
                $ref: "./data/skills.json"

  /experience:
    get:
      summary: Experience
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: 
                [{
                  "company": "company name",
                  "position": "System analyst",
                  "period": "2020-now"
                }]