openapi: 3.0.0
info:
  title: Nalobin Igor
  version: 1.0.0
  description: |
    ## API CV

servers:
  - url: https://igor-nalobin.github.io/igor-nalobin

paths:
  /about:
    get:
      summary: Common
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: |
                {
                  "name": "Igor Nalobin",
                  "profession": "System analyst",
                  "email": "i.v.nalobin@gmail.com"
                }

  /skills:
    get:
      summary: Skills
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: ["SOAP", "XML", "SQL"]

  /experience:
    get:
      summary: Experience
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: |
                [{
                  "company": "company name",
                  "position": "System analyst",
                  "period": "2020-now"
                }]